apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Content-Type "nosniff";
      proxy_set_header Content-Security-Policy "default-src 'self' * 'unsafe-inline' 'unsafe-eval';";
      proxy_set_header X-XSS-Protection "1; mode=block";
      proxy_set_header X-Frame-Options "SAMEORIGIN";
spec:
  tls:
    - hosts:
      - hidden.mistery
      secretName: dashboard-cert
  rules:
  - host: hidden.mistery
    http:
      paths:
      - path: /*
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80