apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-test
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accesModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-test"